### PR TITLE
dbpedia.org to dati.camera.it

### PR DESCRIPTION
**Pull request by dvcama**
Italian Chamber of Deputies Linked Open Data

### CODE REVIEW

**Comment by jimkont** [comment]
Thanks a lot @dvcama !!!
Could you please provide a sorted dump to make diff easier in future updates?

something like :

```
CONSTRUCT {?b <http://www.w3.org/2002/07/owl#sameAs> ?o} 
        where {
            ?o owl:sameAs ?b.
            FILTER(REGEX(STR(?b),'http://dbpedia.org'))
        }  order by ASC(?b)
        LIMIT 10000
```

**Comment by dvcama** [comment]
Ok, I'll do it but virtuoso seams to have a bug that makes the Iri sort feature fail (at least in this case) 

I'll check it, in the meanwhile I'll submit a bash script to download and sort the data, ok?

**Comment by dvcama** [comment]
ok @jimkont, done!

**Comment by jimkont** [comment]
Perfect!

**Pull request merged**
