### PR TITLE
ja.dbpedia.org to geonames.jp

### PR DESCRIPTION
**Pull request by indigo-lab**
Linkset from DBpedia Japanese to GeoNames.jp.
http://geonames.jp/ is a collection of geonames in Japan.

### CODE REVIEW

**Comment by indigo-lab** [comment]
Ping?

**Comment by fumi** [comment]
HI @indigo-lab,

Thanks for your contribution,
These links look like good, I will include them into DBpedia Japanese. 

@jimkont, could you merge this pull request to the master branch?

**Comment by fumi** [comment]
This linkset has already been included in http://ja.dbpedia.org.

**Comment by indigo-lab** [comment]
@fumi @jimkont Thank you !!

**Pull request merged**
